### ISSUE TITLE
Error: The specified module could not be found.

### ISSUE THREAD

**Issue by billgosse** [xissy/node-boilerpipe#2]
I'm getting module not found error when I try to require boilerpipe.  It seems to be something missing in the node_modules\boilerpipe\node_modules\cof
fee-script\lib\coffee-script\coffee-script.js file. I've included details of the error below along with my npm listing.  Thanks.

C:\Dev\nodework\RSSReaderBoilerPipeDemo>node rssreader.js

C:\Dev\nodework\RSSReaderBoilerPipeDemo\node_modules\boilerpipe\node_modules\cof
fee-script\lib\coffee-script\coffee-script.js:211
      Module._extensions[extension](this, filename);
                                   ^
Error: The specified module could not be found.
C:\Dev\nodework\RSSReaderBoilerPipeDemo\node_modules\boilerpipe\node_modules\jav
a\build\Release\nodejavabridge_bindings.node
    at Module.load (C:\Dev\nodework\RSSReaderBoilerPipeDemo\node_modules\boilerp
ipe\node_modules\coffee-script\lib\coffee-script\coffee-script.js:211:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Dev\nodework\RSSReaderBoilerPipeDemo\node_modules\
boilerpipe\node_modules\java\lib\nodeJavaBridge.js:5:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (C:\Dev\nodework\RSSReaderBoilerPipeDemo\node_modules\boilerp
ipe\node_modules\coffee-script\lib\coffee-script\coffee-script.js:211:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Dev\nodework\RSSReaderBoilerPipeDemo\node_modules\
boilerpipe\node_modules\java\index.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (C:\Dev\nodework\RSSReaderBoilerPipeDemo\node_modules\boilerp
ipe\node_modules\coffee-script\lib\coffee-script\coffee-script.js:211:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Dev\nodework\RSSReaderBoilerPipeDemo\node_modules\
boilerpipe\lib\index.coffee:6:10)
    at Object.<anonymous> (C:\Dev\nodework\RSSReaderBoilerPipeDemo\node_modules\
boilerpipe\lib\index.coffee:256:4)
    at Module._compile (module.js:456:26)
    at Object.loadFile (C:\Dev\nodework\RSSReaderBoilerPipeDemo\node_modules\boi
lerpipe\node_modules\coffee-script\lib\coffee-script\coffee-script.js:182:19)
    at Module.load (C:\Dev\nodework\RSSReaderBoilerPipeDemo\node_modules\boilerp
ipe\node_modules\coffee-script\lib\coffee-script\coffee-script.js:211:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Dev\nodework\RSSReaderBoilerPipeDemo\node_modules\
boilerpipe\index.js:3:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Dev\nodework\RSSReaderBoilerPipeDemo\rssreader.js:
12:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

C:\Dev\nodework\RSSReaderBoilerPipeDemo>npm list
C:\Dev\nodework\RSSReaderBoilerPipeDemo
├─┬ boilerpipe@0.0.4
│ ├── async@0.2.9
│ ├── coffee-script@1.6.3
│ └── java@0.2.3
├─┬ cheerio@0.12.0
│ ├─┬ cheerio-select@0.0.3
│ │ └─┬ CSSselect@0.3.1
│ │   └── CSSwhat@0.2.0
│ ├── entities@0.3.0
│ ├─┬ htmlparser2@3.1.1
│ │ ├── domelementtype@1.1.1
│ │ ├── domhandler@2.0.3
│ │ ├── domutils@1.1.2
│ │ └── readable-stream@1.0.2
│ └── underscore@1.4.4
├── dateformat@1.0.6-1.2.3
├─┬ feedme@0.2.6
│ ├── clarinet@0.7.2
│ ├── eventyoshi@0.1.6
│ └── sax@0.4.3
├─┬ feedparser@0.16.1
│ ├── addressparser@0.1.3
│ ├── array-indexofobject@0.0.1
│ ├── readable-stream@1.0.2
│ ├─┬ request@2.21.0
│ │ ├── aws-sign@0.3.0
│ │ ├── cookie-jar@0.3.0
│ │ ├── forever-agent@0.5.0
│ │ ├─┬ form-data@0.0.8
│ │ │ ├── async@0.2.9
│ │ │ └─┬ combined-stream@0.0.4
│ │ │   └── delayed-stream@0.0.5
│ │ ├─┬ hawk@0.13.1
│ │ │ ├─┬ boom@0.4.2
│ │ │ │ └── hoek@0.9.1
│ │ │ ├── cryptiles@0.2.2
│ │ │ ├── hoek@0.8.5
│ │ │ └─┬ sntp@0.2.4
│ │ │   └── hoek@0.9.1
│ │ ├─┬ http-signature@0.9.11
│ │ │ ├── asn1@0.1.11
│ │ │ ├── assert-plus@0.1.2
│ │ │ └── ctype@0.5.2
│ │ ├── json-stringify-safe@4.0.0
│ │ ├── mime@1.2.9
│ │ ├── node-uuid@1.4.0
│ │ ├── oauth-sign@0.3.0
│ │ ├── qs@0.6.5
│ │ └── tunnel-agent@0.3.0
│ ├── resanitize@0.1.11
│ └── sax@0.5.4
├─┬ htmlparser2@3.1.5
│ ├── domelementtype@1.1.1
│ ├── domhandler@2.0.3
│ ├── domutils@1.1.2
│ └── readable-stream@1.0.2
├─┬ mongodb@1.3.12
│ ├── bson@0.2.1
│ └── kerberos@0.0.3
├─┬ mongoose@3.6.15
│ ├── hooks@0.2.1
│ ├─┬ mongodb@1.3.11
│ │ ├── bson@0.1.9
│ │ └── kerberos@0.0.3
│ ├── mpath@0.1.1
│ ├─┬ mpromise@0.2.1
│ │ └── sliced@0.0.4
│ ├── ms@0.1.0
│ ├── muri@0.3.1
│ ├── regexp-clone@0.0.1
│ └── sliced@0.0.3
├─┬ mysql@2.0.0-alpha8
│ ├── bignumber.js@1.0.1
│ └── require-all@0.0.3
├─┬ request@2.25.0
│ ├── aws-sign@0.3.0
│ ├── cookie-jar@0.3.0
│ ├── forever-agent@0.5.0
│ ├─┬ form-data@0.1.0
│ │ ├── async@0.2.9
│ │ └─┬ combined-stream@0.0.4
│ │   └── delayed-stream@0.0.5
│ ├─┬ hawk@1.0.0
│ │ ├── boom@0.4.2
│ │ ├── cryptiles@0.2.2
│ │ ├── hoek@0.9.1
│ │ └── sntp@0.2.4
│ ├─┬ http-signature@0.10.0
│ │ ├── asn1@0.1.11
│ │ ├── assert-plus@0.1.2
│ │ └── ctype@0.5.2
│ ├── json-stringify-safe@5.0.0
│ ├── mime@1.2.9
│ ├── node-uuid@1.4.0
│ ├── oauth-sign@0.3.0
│ ├── qs@0.6.5
│ └── tunnel-agent@0.3.0
├─┬ rssparser@0.0.4
│ ├─┬ request@2.16.6
│ │ ├── aws-sign@0.2.0
│ │ ├── cookie-jar@0.2.0
│ │ ├── forever-agent@0.2.0
│ │ ├─┬ form-data@0.0.7
│ │ │ ├── async@0.1.22
│ │ │ └─┬ combined-stream@0.0.4
│ │ │   └── delayed-stream@0.0.5
│ │ ├─┬ hawk@0.10.2
│ │ │ ├── boom@0.3.8
│ │ │ ├── cryptiles@0.1.3
│ │ │ ├── hoek@0.7.6
│ │ │ └── sntp@0.1.4
│ │ ├── json-stringify-safe@3.0.0
│ │ ├── mime@1.2.9
│ │ ├── node-uuid@1.4.0
│ │ ├── oauth-sign@0.2.0
│ │ ├── qs@0.5.5
│ │ └── tunnel-agent@0.2.0
│ ├── underscore@1.4.4
│ ├─┬ vows@0.7.0
│ │ ├── diff@1.0.4
│ │ └── eyes@0.1.8
│ └─┬ xml2js@0.2.6
│   └── sax@0.4.2
└── string@1.5.0

C:\Dev\nodework\RSSReaderBoilerPipeDemo>

**Comment by billgosse** [comment]
I think I figured this out. I don't think I was compiling some of the java node stuff quite right.  After fixing my visual studio stuff and performing a fresh npm install everything started working correctly.

**Comment by xissy** [comment]
Hello, @billgosse!

I'm late to check this issue but it's nice that you already solved the problem.

Good luck!

**Comment by billgosse** [comment]
Hi Taeho,

Thanks for your reply. I do have one question. Is there a way to set parameters for the JVM such max heap?

Thanks,

Bill

**Comment by xissy** [comment]
I was looking for it for a while but unfortunately I couldn't find the answer.
If you meet how to set jvm parameters then please let me know too.

Thank you.

**Comment by billgosse** [comment]
Ok, I think that java bridge your using must be using JNI somehow so maybe the answer is there.

**Comment by billgosse** [comment]
I found this in one of the closed issue comments which looks like the answer:

I also just added the ability to add JVM start options. You need to call this before the VM gets created so preferably right after the first require statement for node-java (see the unit test testHelper.js file for an example).

java.options.push("-Djava.awt.headless=true");

From: Bill Gosse [mailto:bill.gosse@salesquest.com] 
Sent: Monday, August 12, 2013 9:27 AM
To: 'xissy/node-boilerpipe'
Subject: RE: [node-boilerpipe] Error: The specified module could not be found. (#2)

Ok, I think that java bridge your using must be using JNI somehow so maybe the answer is there.

**Comment by xissy** [comment]
Wow, Great! @billgosse

**Comment by billgosse** [comment]
By the way thanks for building this module.  It works really great. We use Boilerpipe with some of our java applications. We’re just getting into node.js.
